"use client";
import {useEffect,useState} from "react";import type {VirtualTradingState} from "../../db/virtual-trading";import type {UserPlan} from "../../db/plans";import type {AiTradingSettings} from "../../db/ai-trading";
export function AiAutoTrader({environment,plan,onState}:{environment:"virtual"|"current";plan:UserPlan;onState:(s:VirtualTradingState)=>void}){
 const [settings,setSettings]=useState<AiTradingSettings|null>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("Loading persistent AI settings…");
 useEffect(()=>{fetch("/api/ai-trade",{cache:"no-store"}).then(r=>r.json()).then((d:{settings?:AiTradingSettings})=>{if(d.settings)setSettings(d.settings)}).catch(()=>setStatus("Unable to load AI settings."))},[]);
 useEffect(()=>{if(settings&&settings.environment!==environment)void save({...settings,environment},false)},[environment]);
 async function save(next:AiTradingSettings,announce=true){setBusy(true);try{const r=await fetch("/api/ai-trade",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const d=await r.json() as {settings?:AiTradingSettings;error?:string};if(!r.ok||!d.settings)throw new Error(d.error||"Unable to save settings.");setSettings(d.settings);if(announce)setStatus(d.settings.isEnabled?"AI Auto Trade is enabled and continues through the background scheduler.":"AI Auto Trade is disabled.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to save settings.");}finally{setBusy(false)}}
 async function scan(){setBusy(true);try{const r=await fetch("/api/ai-trade",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({force:true})});const d=await r.json() as {state?:VirtualTradingState;decision?:{side?:string;strategy?:string;confidence?:number;reason?:string;marketSymbol?:string};settings?:AiTradingSettings;error?:string};if(!r.ok||!d.state)throw new Error(d.error||"AI scan failed.");onState(d.state);if(d.settings)setSettings(d.settings);const x=d.decision;setStatus(x?.side==="hold"?`No trade: ${x.reason}`:`${x?.strategy} opened a ${x?.side?.toUpperCase()} ${x?.marketSymbol??"position"} (${x?.confidence}% confidence).`);}catch(e){setStatus(e instanceof Error?e.message:"AI scan failed.");}finally{setBusy(false)}}
 if(!settings)return <section className="ai-trader-panel"><p>{status}</p></section>;
 return <section className="ai-trader-panel ai-settings-panel"><div className="ai-heading"><span className="ai-live-dot"/><div><strong>AI Auto Trade</strong><p>{plan.name} · persists across pages · server scheduled</p></div></div><div className="ai-trader-actions"><button className={`switch-button ${settings.isEnabled?"active":""}`} aria-pressed={settings.isEnabled} disabled={busy} onClick={()=>save({...settings,isEnabled:!settings.isEnabled})} type="button"><span/>{settings.isEnabled?"Enabled":"Disabled"}</button><button disabled={busy} onClick={scan} type="button">{busy?"Saving…":"Run scan now"}</button></div><div className="ai-settings-grid"><label>Strategy<select value={settings.preferredStrategy} onChange={e=>setSettings({...settings,preferredStrategy:e.target.value})}><option value="auto">Automatic best strategy</option><option value="scalping">Scalping momentum</option><option value="rsi">RSI</option><option value="bollinger">Bollinger Bands</option></select></label><label>Volume per position<input min="0.0001" step="0.0001" type="number" value={settings.volume} onChange={e=>setSettings({...settings,volume:Number(e.target.value)})}/></label><label>Take Profit (%)<input min="0.1" max="100" step="0.1" type="number" value={settings.takeProfitBps/100} onChange={e=>setSettings({...settings,takeProfitBps:Math.round(Number(e.target.value)*100)})}/></label><label>Stop Loss (%)<input min="0.1" max="50" step="0.1" type="number" value={settings.stopLossBps/100} onChange={e=>setSettings({...settings,stopLossBps:Math.round(Number(e.target.value)*100)})}/></label><label className="ai-auto-close"><input checked={settings.autoClose} onChange={e=>setSettings({...settings,autoClose:e.target.checked})} type="checkbox"/> Auto-close AI positions on a strong opposite strategy signal</label><button className="save-ai-settings" disabled={busy} onClick={()=>save(settings)} type="button">Save AI settings</button></div><p className="ai-trader-status" aria-live="polite">{status}</p></section>;
}
