"use client";
import {useState} from "react";
import type {BillingCycle,TradingPlan,UserPlan} from "../../db/plans";
const benefits:Record<string,string[]>={starter:["RSI and momentum scalping","1 simultaneous AI position","Scan every 120 seconds","Basic TP/SL automation"],pro:["RSI, Bollinger Bands and trend filters","Up to 3 simultaneous AI positions","Scan every 60 seconds","Background strategy exits","Custom volume, TP and SL"],elite:["All Pro strategies","Multi-window strategy confirmation","Volatility filtering","Up to 6 simultaneous AI positions","Priority 60-second background runner","Advanced automatic exits"]};
export function PlanCards({plans,initialPlan}:{plans:TradingPlan[];initialPlan:UserPlan}){
 const [current,setCurrent]=useState(initialPlan);const [cycle,setCycle]=useState<BillingCycle>("monthly");const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
 const money=(v:number,c:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(v/100);
 async function buy(plan:TradingPlan){setBusy(plan.id);setMessage(null);try{const r=await fetch("/api/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planId:plan.id,billingCycle:cycle})});const d=await r.json() as {currentPlan?:UserPlan;error?:string};if(!r.ok||!d.currentPlan)throw new Error(d.error||"Unable to purchase plan.");setCurrent(d.currentPlan);setMessage(`${d.currentPlan.name} ${d.currentPlan.billingCycle??""} plan is now active.`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to purchase plan.");}finally{setBusy(null)}}
 return <><div className="plan-current-banner"><div><span>ACTIVE AI PLAN</span><strong>{current.name}</strong><p>{current.status==="active"?(current.endsAt?`${current.billingCycle} access until ${new Date(current.endsAt).toLocaleDateString("en-GB")}`:"Active with no expiry"):"Default Starter access"}</p></div><a href="/trade">Open AI Trade</a></div><div className="billing-toggle" role="group" aria-label="Billing cycle"><button className={cycle==="monthly"?"active":""} onClick={()=>setCycle("monthly")} type="button">Monthly</button><button className={cycle==="yearly"?"active":""} onClick={()=>setCycle("yearly")} type="button">Yearly <span>Save more</span></button></div>{message&&<p className="plan-message" role="status">{message}</p>}<section className="plan-grid">{plans.map((plan,index)=>{const price=cycle==="yearly"?plan.yearlyPriceMinor:plan.priceMinor;return <article className={`plan-card ${plan.code==="elite"?"featured":""}`} key={plan.id} style={{animationDelay:`${index*90}ms`}}><div><span className="plan-tier">TIER {index+1} · {plan.name}</span><h2>{money(price,plan.currency)}<small>/{cycle==="yearly"?"year":"month"}</small></h2><p>{plan.description}</p>{plan.code!=="starter"&&<p className="plan-duration">{cycle==="monthly"?"Valid for 1 month":"Valid for 12 months"}</p>}</div><ul>{benefits[plan.code].map(item=><li key={item}>{item}</li>)}</ul><div className="plan-difference"><strong>Plan difference</strong><span>Strategy level {plan.strategyLevel}</span><span>{plan.maxOpenPositions} maximum AI positions</span><span>{(plan.riskPerTradeBps/100).toFixed(2)}% plan risk allocation</span></div><button disabled={busy!==null||(current.id===plan.id&&current.billingCycle===cycle)} onClick={()=>buy(plan)} type="button">{current.id===plan.id&&current.billingCycle===cycle?"Current plan":busy===plan.id?"Purchasing…":plan.priceMinor===0?"Choose Starter":`Purchase ${cycle}`}</button></article>})}</section><p className="plan-disclaimer">Purchases use Current Balance. Higher tiers unlock more tools and capacity, but no plan guarantees profit or a win rate.</p></>;
}
