"use client";
import Link from "next/link";import {useState} from "react";import type {DashboardEnvironment,TradingDashboardData} from "../../db/dashboard";
export function TradingDashboard({data,name,email}:{data:TradingDashboardData;name:string;email:string}){const [env,setEnv]=useState<DashboardEnvironment>("current");const [animationKey,setAnimationKey]=useState(0);const account=data[env];const money=(v:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:account.currency}).format(v/100);function change(next:DashboardEnvironment){if(next===env)return;setEnv(next);setAnimationKey(v=>v+1)}return <>
<header className="dashboard-heading"><div><p className="eyebrow">TRADING DASHBOARD</p><h1>Welcome, {name}.</h1><p>Monitor balances, AI plan, positions, orders, and profit and loss.</p></div><div className="balance-toggle dashboard-balance-toggle animated-toggle" role="group" aria-label="Dashboard account"><span className={env==="virtual"?"toggle-slider virtual":"toggle-slider"}/><button type="button" className={env==="current"?"active":""} onClick={()=>change("current")}>Current Balance</button><button type="button" className={env==="virtual"?"active":""} onClick={()=>change("virtual")}>Virtual Balance</button></div></header>
<section className="dashboard-grid trading-summary-grid dashboard-card-stage" key={animationKey}>
<article className="dashboard-card dashboard-card-primary animated-card"><span className="dashboard-card-label">{env==="current"?"CURRENT BALANCE":"VIRTUAL BALANCE"}</span><h2>{money(account.balanceMinor)}</h2><p>{env==="current"?"System-only account funds used by non-virtual environments.":"Practice funds used exclusively by the Virtual environment."}</p><div className="dashboard-card-footer"><Link href="/trade">Open Trade</Link><strong>USD</strong></div></article>
<Metric label="TOTAL P&L" value={money(account.totalPnlMinor)} detail={`Realized ${money(account.realizedPnlMinor)} · Floating ${money(account.unrealizedPnlMinor)}`} pnl={account.totalPnlMinor}/><Metric label="OPEN POSITIONS" value={String(account.openPositions)} detail={`${account.pendingOrders} pending orders`}/><Metric label="TRADE RESULTS" value={`${account.winningTrades}W / ${account.losingTrades}L`} detail={`Recent volume ${money(account.tradedVolumeMinor)}`}/>
</section>
<section className="dashboard-grid pnl-breakdown-grid dashboard-card-stage" key={`p-${animationKey}`}><Metric label="REALIZED P&L" value={money(account.realizedPnlMinor)} detail="Profit or loss from closed positions" pnl={account.realizedPnlMinor}/><Metric label="UNREALIZED P&L" value={money(account.unrealizedPnlMinor)} detail="Live floating P&L from open positions" pnl={account.unrealizedPnlMinor}/><article className="dashboard-card ai-plan-dashboard-card animated-card"><span className="dashboard-card-label">AI TRADING PLAN</span><h2>{data.plan.name}</h2><p>Strategy level {data.plan.strategyLevel} · {data.plan.maxOpenPositions} max AI positions · scans every {data.plan.scanIntervalSeconds}s</p><div className="dashboard-card-footer"><Link href="/plans">Manage plan</Link><strong>{data.plan.status==="active"?"Active":"Starter"}</strong></div></article></section>
<section className="ledger-section"><header className="ledger-heading"><div><p className="eyebrow">RECENT TRADING ACTIVITY</p><h2>{env==="current"?"Current":"Virtual"} account trades</h2></div><Link href="/trade">View terminal</Link></header>{account.recentTrades.length?<div className="ledger-list">{account.recentTrades.map(t=><article className="ledger-row" key={t.id}><div className="ledger-description"><span className={`ledger-indicator ${t.side==="buy"?"ledger-indicator-credit":"ledger-indicator-debit"}`}/><div><strong>{t.marketSymbol} · {t.side.toUpperCase()}</strong><span>{new Date(t.createdAt).toLocaleString("en-MY")}</span></div></div><div className="ledger-amount"><strong>{t.quantity.toLocaleString()}</strong><span>{t.price===null?t.status:`${t.status} @ ${t.price.toLocaleString()}`}</span></div></article>)}</div>:<div className="ledger-empty"><strong>No trade activity yet</strong><p>Orders and closed positions for this account will appear here.</p></div>}</section>
</>}
function Metric({label,value,detail,pnl}:{label:string;value:string;detail:string;pnl?:number}){return <article className="dashboard-card animated-card"><span className="dashboard-card-label">{label}</span><h2 className={pnl===undefined?"":pnl>0?"pnl-positive":pnl<0?"pnl-negative":""}>{value}</h2><p>{detail}</p></article>}
